services:
  akbi-be:
    container_name: akbi-be
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - app-net
    env_file:
      - .env

networks:
  app-net:
   external: true	