name: Back-End Action
run-name: ${{ github.actor }} is running actions 🚀
on:
    push:
        branches:
            - main
        paths:
            - backend/**
jobs:
    deploy_on_server:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Deploy backend on server 🚀
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  command_timeout: 30m
                  script: |
                      cd ~/akbi
                      docker compose down backend
                      docker compose up -d --build backend
